# Generated by Django 3.0.3 on 2020-05-29 00:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='商品名')),
                ('price', models.IntegerField(default=0, verbose_name='単価')),
                ('including_tax', models.BooleanField(default=False, verbose_name='税込')),
                ('unit', models.CharField(default='個', max_length=10, verbose_name='単位')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='在庫数')),
                ('moq', models.IntegerField(blank=True, default=0, null=True, verbose_name='最低発注数量')),
                ('spq', models.IntegerField(blank=True, default=0, null=True, verbose_name='最小発注単位')),
                ('category1', models.CharField(blank=True, max_length=30, null=True, verbose_name='カテゴリ1')),
                ('category2', models.CharField(blank=True, max_length=30, null=True, verbose_name='カテゴリ2')),
                ('category3', models.CharField(blank=True, max_length=30, null=True, verbose_name='カテゴリ3')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品画像')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='販売可否')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '商品',
                'db_table': 'item',
            },
        ),
    ]
