# Generated by Django 3.1.3 on 2020-11-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200730_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='商品説明'),
        ),
    ]
