# Generated by Django 3.1.3 on 2020-12-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='商品説明'),
        ),
    ]
