# Generated by Django 3.1.3 on 2021-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20201231_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available_stock',
            field=models.IntegerField(default=0, verbose_name='有効在庫数'),
        ),
        migrations.AddField(
            model_name='item',
            name='reserved_stock',
            field=models.IntegerField(default=0, verbose_name='引当在庫数'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='在庫数'),
        ),
    ]
