# Generated by Django 3.1.3 on 2021-02-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20210128_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reserved_stock',
        ),
    ]
