# Generated by Django 3.0.3 on 2020-03-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200318_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='携帯番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='電話番号'),
        ),
    ]
