# Generated by Django 3.1.3 on 2020-12-31 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='カート作成日時'),
        ),
    ]
