# Generated by Django 3.1.3 on 2021-02-01 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210201_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='カート作成日時'),
        ),
    ]
