# Generated by Django 3.0.3 on 2020-07-26 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20200725_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='購入者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='including_tax',
            field=models.BooleanField(default=False, verbose_name='税込'),
        ),
        migrations.AddField(
            model_name='order',
            name='moq',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最低発注数量'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='DUMMY', max_length=40, unique=True, verbose_name='商品名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品画像'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0, verbose_name='単価'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='販売者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='spq',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最小発注単位'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(default='個', max_length=10, verbose_name='単位'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
