# Generated by Django 3.0.3 on 2020-07-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200726_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
