# Generated by Django 3.0.3 on 2020-03-18 04:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='商品名')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='単価')),
                ('including_tax', models.BooleanField(default=False, verbose_name='税込')),
                ('unit', models.CharField(default='個', max_length=10, verbose_name='単位')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='在庫数')),
                ('category1', models.CharField(max_length=30, verbose_name='カテゴリ1')),
                ('category2', models.CharField(max_length=30, verbose_name='カテゴリ2')),
                ('category3', models.CharField(max_length=30, verbose_name='カテゴリ3')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品画像')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '商品',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='注文日')),
                ('deliverly_date', models.DateTimeField(blank=True, null=True, verbose_name='納品日')),
                ('shipment_date', models.DateTimeField(blank=True, null=True, verbose_name='発送日')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='キャンセル')),
                ('remarks', models.TextField(max_length=400, verbose_name='備考')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Item', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '注文明細',
                'db_table': 'order',
            },
        ),
    ]
