# Generated by Django 3.0.3 on 2020-05-29 00:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='注文日')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='納品日')),
                ('shipment_date', models.DateTimeField(blank=True, null=True, verbose_name='発送日')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='キャンセル')),
                ('remarks', models.TextField(blank=True, max_length=150, null=True, verbose_name='備考')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Item', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '注文明細',
                'db_table': 'order',
            },
        ),
    ]
