# Generated by Django 3.0.3 on 2020-03-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='カテゴリ1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='カテゴリ2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='カテゴリ3'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='単価'),
        ),
    ]
