# Generated by Django 3.0.3 on 2020-03-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200318_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliverly_date',
            new_name='delivery_date',
        ),
        migrations.AddField(
            model_name='item',
            name='moq',
            field=models.IntegerField(blank=True, null=True, verbose_name='最低発注数量'),
        ),
        migrations.AddField(
            model_name='item',
            name='spq',
            field=models.IntegerField(blank=True, null=True, verbose_name='最小発注単位'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='商品名'),
        ),
    ]
