# Generated by Django 3.0.3 on 2020-04-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200328_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='販売可否'),
        ),
        migrations.AlterField(
            model_name='item',
            name='moq',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最低発注数量'),
        ),
        migrations.AlterField(
            model_name='item',
            name='spq',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最小発注単位'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='備考'),
        ),
    ]
