# Generated by Django 3.0.3 on 2020-07-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200726_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='total_unit',
            field=models.IntegerField(default=0, verbose_name='商品点数'),
        ),
    ]
