# Generated by Django 3.0.3 on 2020-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200727_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.CharField(default='dummy_cart_id', max_length=40, verbose_name='カートID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='dummy_name', max_length=40, unique=True, verbose_name='商品名'),
        ),
    ]
