# Generated by Django 3.0.3 on 2020-07-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.CharField(default='dummy_item_id', max_length=40, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='dummy_name', max_length=40, verbose_name='商品名'),
        ),
    ]
