# Generated by Django 3.0.3 on 2020-08-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200730_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='納品完了フラグ'),
        ),
    ]
