# Generated by Django 3.1.3 on 2021-01-31 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_auto_20201231_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_in_order', to=settings.AUTH_USER_MODEL, verbose_name='購入者'),
        ),
    ]
